export const PROGRAM_FAQS = [
  { q: "Do we need to be in conflict first?", a: "No. The best time is before the first real fight — when you can still choose clarity over self-protection." },
  { q: "Can one of us do this alone?", a: "No — the founding cohort is for pairs. Both co-founders take part and you enroll together; the whole method is about verifying that the two of you actually understand each other, which only works with both in the room." },
  { q: "How is this different from therapy?", a: "Therapy explores feelings. The program teaches you a protocol. By the end, you can surface contradictions and close gaps yourselves — that's the point." },
  { q: "What happens after the program?", a: "You keep the process. The Partner Agreement isn't a one-time document — it's a practice. When a new decision comes up, you already know how to check whether you actually agree." },
  { q: "What if it surfaces something we can't fix?", a: "Then you find out now, with two sessions invested, instead of two years and a cap table. Most gaps are bridgeable. The ones that aren't — you needed to know." },
];

export const KEY_HIRE_FAQS = [
  { q: "Free 90 minutes? What are you actually selling me?", a: "A paid engagement, eventually. That's the honest answer. I give the audit away because describing what I do doesn't work and doing it does, so I'd rather you see it and decide from there. If you want to keep going afterwards I'll tell you what it costs." },
  { q: "My hire is fine. We talk every week, I do 1:1s.", a: "Weekly 1:1s are usually where this hides, not where it shows up. The question isn't how often you talk, it's when your hire last told you that you were wrong about something that mattered, and what happened after. If you can't name that moment, that isn't proof of a problem, but it's the thing worth looking at." },
  { q: "How is this different from just asking them?", a: "Ask them. Most founders get some version of 'yeah, all good,' and that's not because the person is dishonest. You control their salary, their scope, and whether they're here next year, so telling you you're wrong is a risk with no upside for them. That's also why asking harder backfires: more pressure from your side of the table gets you more agreement, not more truth." },
  { q: "Shouldn't my hire be in the room?", a: "No, and that's deliberate. The session isn't about them, it's about how you create alignment: what you believe caused the misalignments you've already had, what you tried, what you never tried. Putting them in the room turns it into mediation and asks them to be candid in front of the person who signs their payroll, which is the exact problem we're looking at." },
  { q: "Isn't this just coaching? Or therapy?", a: "No. Coaching works on you over months, and therapy works on why you are the way you are. This is one live conversation about one mechanism: how understanding gets built between you and this person, and where it quietly doesn't. No program, no homework." },
];
