/**
 * @file p704-anon-one-to-many-token.spec.ts
 * @description P704 canary: anonymous one-to-many token reading must NOT call token RPCs
 * that the P684 guard blocks for anon callers.
 *
 * BEFORE FIX: Clicking "Open Letter" fires updateDeliveryStatusByToken → 400 →
 *   console.error "[db-error] updateDeliveryStatusByToken: ..." containing
 *   "Authentication required for one-to-many responses".
 *   Clicking a position button fires submitPointResponseByToken → 400 → same error + page error.
 *
 * AFTER FIX: bufferOnly=true → no token RPCs fired → no console errors; position updates
 *   local state only, responses buffered for confirm-letter-response after signup.
 */

import { test, expect } from '@playwright/test';
import { supabaseAdmin } from './helpers/supabase-admin';
import { createTestUser, deleteTestUser, type TestUser } from './helpers/test-user';
import { createTestStory, deleteTestStory } from './helpers/test-story';
import { createTestPoint, deleteTestPoint } from './helpers/test-point';

test.describe('P704: Anon one-to-many token reading — no authentication errors', () => {
  test.describe.configure({ timeout: 60_000 });

  let sender: TestUser;
  let docId: string;
  let storyId: string;
  let point1Id: string;
  let point2Id: string;
  let letterId: string;
  let deliveryId: string;
  let deliveryToken: string;

  test.beforeAll(async () => {
    sender = await createTestUser({ name: 'P704 Sender' });

    // Create story + 2 points (2 visible points → point-engage phase on open)
    const story = await createTestStory(sender.user.id, {
      title: 'P704 False Consensus Test',
      content: 'Testing anon one-to-many reading without 400 errors.',
    });
    storyId = story.id;

    const point1 = await createTestPoint(sender.user.id, {
      statement: 'P704 Point 1: Leaders avoid hard conversations.',
    });
    point1Id = point1.id;

    const point2 = await createTestPoint(sender.user.id, {
      statement: 'P704 Point 2: Clarity requires courage.',
    });
    point2Id = point2.id;

    // Set sender positions so the story is display-ready
    await supabaseAdmin.from('point_positions').upsert([
      { point_id: point1Id, user_id: sender.user.id, position: 'agree' },
      { point_id: point2Id, user_id: sender.user.id, position: 'agree' },
    ]);

    // Get auto-generated story version
    const { data: version, error: versionError } = await supabaseAdmin
      .from('story_versions')
      .select('id')
      .eq('story_id', storyId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();
    if (!version || versionError) throw new Error(`Story version not found: ${versionError?.message}`);

    // Create sealed one-to-many doc (required for letter)
    const { data: doc, error: docError } = await supabaseAdmin
      .from('clarity_docs')
      .insert({ owner_id: sender.user.id, title: 'P704 Doc', visibility: 'public' })
      .select('id')
      .single();
    if (!doc || docError) throw new Error(`Doc creation failed: ${docError?.message}`);
    docId = doc.id;

    // Create sealed one-to-many letter
    const { data: letter, error: letterError } = await supabaseAdmin
      .from('clarity_letters')
      .insert({
        source_doc_id: doc.id,
        sender_id: sender.user.id,
        mode: 'one-to-many',
        status: 'sealed',
        sealed_at: new Date().toISOString(),
      })
      .select('id')
      .single();
    if (!letter || letterError) throw new Error(`Letter creation failed: ${letterError?.message}`);
    letterId = letter.id;

    // Create snapshot with 2 visible points → triggers point-engage phase
    const { error: snapshotError } = await supabaseAdmin
      .from('letter_story_snapshots')
      .insert({
        letter_id: letterId,
        story_id: storyId,
        version_id: version.id,
        position: 0,
        visibility: 'public',
        point_config: {
          storyTitle: 'P704 False Consensus Test',
          storyText: 'Testing anon one-to-many reading without 400 errors.',
          points: [
            { id: point1Id, text: 'P704 Point 1: Leaders avoid hard conversations.', authorPosition: 'agree' },
            { id: point2Id, text: 'P704 Point 2: Clarity requires courage.', authorPosition: 'agree' },
          ],
        },
      });
    if (snapshotError) throw new Error(`Snapshot creation failed: ${snapshotError.message}`);

    // Create delivery (invitation_token auto-generated by DB)
    const { data: delivery, error: deliveryError } = await supabaseAdmin
      .from('letter_deliveries')
      .insert({ letter_id: letterId, receiver_email: null, receiver_profile_id: null, status: 'sent' })
      .select('id, invitation_token')
      .single();
    if (!delivery || deliveryError) throw new Error(`Delivery creation failed: ${deliveryError?.message}`);
    deliveryId = delivery.id;
    deliveryToken = delivery.invitation_token;
  });

  test.afterAll(async () => {
    if (letterId) {
      const { data: deliveries } = await supabaseAdmin
        .from('letter_deliveries')
        .select('id')
        .eq('letter_id', letterId);
      if (deliveries?.length) {
        await supabaseAdmin
          .from('letter_point_responses')
          .delete()
          .in('delivery_id', deliveries.map((d) => d.id));
      }
      await supabaseAdmin
        .from('story_verifications')
        .delete()
        .eq('story_id', storyId)
        .eq('source', 'letter');
      await supabaseAdmin.from('clarity_letters').delete().eq('id', letterId);
    }
    if (docId) await supabaseAdmin.from('clarity_docs').delete().eq('id', docId);
    if (point1Id) await deleteTestPoint(point1Id);
    if (point2Id) await deleteTestPoint(point2Id);
    if (storyId) await deleteTestStory(storyId);
    if (sender?.user?.id) await deleteTestUser(sender.user.id);
  });

  test('smoke: anon recipient sees cover page via one-to-many token', async ({ page }) => {
    await page.goto(`/letter/${deliveryId}?token=${deliveryToken}`);
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('button', { name: /open the letter/i })).toBeVisible({ timeout: 10_000 });
  });

  test('opening letter does not produce authentication errors in console', async ({ page }) => {
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('pageerror', (err) => consoleErrors.push(err.message));

    // Navigate as anonymous (no setTestSession)
    await page.goto(`/letter/${deliveryId}?token=${deliveryToken}`);
    await page.waitForLoadState('networkidle');

    const openBtn = page.getByRole('button', { name: /open the letter/i });
    await expect(openBtn).toBeVisible({ timeout: 10_000 });

    // Before fix: clicking Open fires updateDeliveryStatusByToken → 400 → console.error
    await openBtn.click();

    // Allow async RPC to settle
    await page.waitForTimeout(2000);

    const authErrors = consoleErrors.filter((e) =>
      e.includes('Authentication required for one-to-many responses')
    );
    expect(
      authErrors,
      `Expected no "Authentication required" errors. Got: ${authErrors.join(' | ')}`
    ).toHaveLength(0);
  });

  test('submitting a point position does not produce authentication errors', async ({ page }) => {
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
    page.on('pageerror', (err) => consoleErrors.push(err.message));

    await page.goto(`/letter/${deliveryId}?token=${deliveryToken}`);
    await page.waitForLoadState('networkidle');

    const openBtn = page.getByRole('button', { name: /open the letter/i });
    await expect(openBtn).toBeVisible({ timeout: 10_000 });
    await openBtn.click();

    // With 2 visible points, flow starts at point-engage phase immediately.
    // Position buttons (Agree/Disagree/Neutral) should appear.
    const agreeBtn = page.getByRole('button', { name: /^agree$/i }).first();
    await expect(agreeBtn).toBeVisible({ timeout: 10_000 });

    // Before fix: clicking triggers submitPointResponseByToken → 400 → console.error + page error
    await agreeBtn.click();

    // Allow async RPC (or skipped RPC after fix) to settle
    await page.waitForTimeout(2000);

    const authErrors = consoleErrors.filter((e) =>
      e.includes('Authentication required for one-to-many responses')
    );
    expect(
      authErrors,
      `Expected no "Authentication required" errors after position submit. Got: ${authErrors.join(' | ')}`
    ).toHaveLength(0);
  });
});
