#!/usr/bin/env bash
# scripts/audit-credential-drift.test.sh — exercise every finding class of
# scripts/audit-credential-drift.sh (P1147), especially its failure path.
#
# Generated by /generate-tests BEFORE scripts/audit-credential-drift.sh exists.
# That is expected TDD-red state, not a bug in this harness — see the FATAL
# check right below. /dev builds the script to make these cases pass.
#
# ============================================================================
# CLI CONTRACT THIS HARNESS ASSUMES (a /generate-tests SUGGESTION, not a
# locked decision — P1147 carries no /architect: pipeline_ran is
# [create-spec, challenge-prd] only). If /dev's implementation uses different
# flags or output tokens, update the fixtures/assertions below to match — but
# the INVARIANTS each case protects come straight from the spec's Done-When
# and must keep being enforced by *some* form of these cases:
#
#   scripts/audit-credential-drift.sh --parse-only --env-dir DIR
#       -> CLASSIFIED:<KEY>:<file>:<line> | UNPARSEABLE:<file>:<line>
#          for every non-blank, non-comment line. Zero silently dropped.
#
#   scripts/audit-credential-drift.sh --audit --env-dir DIR \
#       --registry FILE [--registry FILE ...] [--consumers-dir DIR] \
#       [--not-enumerated NAME:REASON ...]
#       -> CONSUMER_ONLY:<KEY>:<file>:<line>                    (consumer -> registry)
#          REGISTRY_ONLY:<KEY>:<registry-file>                  (registry -> consumer, missing)
#          REGISTRY_LOCATION_MISMATCH:<KEY>:<registry-file>:claimed=<f>:found=<f>
#          REGISTRY_MISMATCH:<KEY>:<reg-a>:<field>=<v>:<reg-b>:<field>=<v>  (registry -> registry)
#          RETIREMENT_CANDIDATE:<KEY>:<registry-file>
#          CONSUMER_LIST_STALE:<KEY>:<registry-file>:documented=<n>:live=<n>
#          NOT_ENUMERATED:<surface>:<reason>                    (excluded from COVERAGE)
#          PLAINTEXT_IN_REGISTRY:<KEY>:<registry-file>:fingerprint=<fp>  (hard fail, exit 1)
#          COVERAGE:<classified>/<total-reachable>:not-enumerated=<n>
#       Fingerprint format: first2…last2(length), e.g. Fa…12(27). Never a raw value.
#
# Output contract: no >, <, or | at word boundaries (shell-safety.md P783) —
# applies to both the script under test and this harness's own PASS/FAIL lines.
#
# All fixtures below are 100% synthetic (FAKE_*/UAT_* names, made-up values).
# None of it is copied from .private/docs/accounts.md, .private/docs/
# edge-function-secrets.md, or any real local env file — per .claude/rules/pii.md
# and this repo's privacy conventions, a committed test file must never carry
# real credential names or values.
# ============================================================================

set -u

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="${REPO_ROOT}/scripts/audit-credential-drift.sh"

if [[ ! -f "$SCRIPT" ]]; then
  echo "FATAL: ${SCRIPT} not found." >&2
  echo "       This harness was generated by /generate-tests (P1147) ahead of the" >&2
  echo "       implementation on purpose (TDD red). /dev must create" >&2
  echo "       scripts/audit-credential-drift.sh implementing the CLI contract" >&2
  echo "       documented at the top of this file before these cases can run." >&2
  exit 2
fi
if [[ ! -x "$SCRIPT" ]]; then
  echo "FATAL: ${SCRIPT} exists but is not executable — chmod +x it." >&2
  exit 2
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/audit-credential-drift-test.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

pass_count=0
fail_count=0
LAST_OUT=""

# run_audit NAME EXPECTED_EXIT -- ARGS...
run_audit() {
  local name="$1" want="$2"; shift 2
  local got=0 out=""
  out="$("$SCRIPT" "$@" 2>&1)" || got=$?
  LAST_OUT="$out"
  if [[ "$got" == "$want" ]]; then
    echo "PASS  ${name}: exit ${got}"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL  ${name}: expected exit ${want}, got ${got}"
    echo "$out" | sed 's/^/        /'
    fail_count=$((fail_count + 1))
  fi
}

# assert_out NAME PATTERN — PATTERN must appear (literal substring) in LAST_OUT
assert_out() {
  if printf '%s\n' "$LAST_OUT" | grep -Fq -- "$2"; then
    echo "PASS  ${1}"
    pass_count=$((pass_count + 1))
  else
    echo "FAIL  ${1}: output did not contain: $2"
    printf '%s\n' "$LAST_OUT" | sed 's/^/        /'
    fail_count=$((fail_count + 1))
  fi
}

# assert_not_out NAME PATTERN — PATTERN must NOT appear in LAST_OUT
assert_not_out() {
  if printf '%s\n' "$LAST_OUT" | grep -Fq -- "$2"; then
    echo "FAIL  ${1}: output contained forbidden text: $2"
    printf '%s\n' "$LAST_OUT" | sed 's/^/        /'
    fail_count=$((fail_count + 1))
  else
    echo "PASS  ${1}"
    pass_count=$((pass_count + 1))
  fi
}

# _fingerprint VALUE — independent oracle for first2…last2(length), computed
# here rather than trusted from the script under test (epistemic.md gate 7b).
_fingerprint() {
  local val="$1" n=${#1}
  printf '%s…%s(%s)' "${val:0:2}" "${val: -2}" "$n"
}

echo "=== audit-credential-drift.sh finding-class suite ==="

# ══════════════════════════════════════════════════════════════════════════
# CASE A — the naive-parser failure path (Done-When #6, #7).
# A well-formed-only fixture certifies nothing (epistemic.md gate 7). This
# fixture mirrors the two real failure shapes named in the spec: a
# lowercase-named line, and lines that yield no key at all (a multi-line
# PEM-style continuation has none of them, and a shell `export a=b` line
# fails on the same lowercase-first-char rule as line 5, from a different
# surface). All values are synthetic.
# ══════════════════════════════════════════════════════════════════════════
CASE_A="${WORK}/case-a"
mkdir -p "$CASE_A"
PARSER_FIXTURE="${CASE_A}/parser-fixture.env"
cat > "$PARSER_FIXTURE" <<'ENV_EOF'
# Fake local env fixture — synthetic values only, not a real credential
FAKE_TEST_API_KEY=placeholder-value-not-a-real-key
FAKE_SERVICE_TOKEN=placeholder-value-not-a-real-token

foo_bar=baz
FAKE_MULTILINE_PEM_KEY="-----BEGIN NOT-A-REAL-CREDENTIAL-BLOCK-----
placeholder-continuation-line-with-no-equals-sign-at-all
-----END NOT-A-REAL-CREDENTIAL-BLOCK-----"
export ANOTHER_LOWERCASE_STYLE_LEAK=nope
ENV_EOF

# Independent oracle: count non-blank, non-comment lines directly from the
# fixture, without trusting the script under test to report its own total.
EXPECTED_TOTAL=$(grep -cvE '^[[:space:]]*($|#)' "$PARSER_FIXTURE")
if [[ "$EXPECTED_TOTAL" != "7" ]]; then
  echo "FAIL  case-A fixture sanity: expected 7 non-blank/non-comment lines in the fixture itself, got ${EXPECTED_TOTAL} — fixture was edited without updating this harness"
  fail_count=$((fail_count + 1))
fi

echo "--- case A: parser failure path ---"
run_audit "parse-only on malformed fixture" 0 --parse-only --env-dir "$CASE_A"

assert_out  "well-formed key 1 classified"         "CLASSIFIED:FAKE_TEST_API_KEY:${PARSER_FIXTURE}:2"
assert_out  "well-formed key 2 classified"         "CLASSIFIED:FAKE_SERVICE_TOKEN:${PARSER_FIXTURE}:3"
assert_out  "PEM opening line classified"          "CLASSIFIED:FAKE_MULTILINE_PEM_KEY:${PARSER_FIXTURE}:6"
assert_out  "Done-When #6: lowercase-named line reported, not silently dropped" \
                                                    "UNPARSEABLE:${PARSER_FIXTURE}:5"
assert_out  "PEM continuation (no '=' at all) reported unparseable" \
                                                    "UNPARSEABLE:${PARSER_FIXTURE}:7"
assert_out  "PEM footer (no '=', non-identifier lead) reported unparseable" \
                                                    "UNPARSEABLE:${PARSER_FIXTURE}:8"
assert_out  "shell export-prefixed lowercase line reported unparseable" \
                                                    "UNPARSEABLE:${PARSER_FIXTURE}:9"

CLASSIFIED_N=$(printf '%s\n' "$LAST_OUT" | grep -cF "CLASSIFIED:")
UNPARSEABLE_N=$(printf '%s\n' "$LAST_OUT" | grep -cF "UNPARSEABLE:")
SUM=$((CLASSIFIED_N + UNPARSEABLE_N))
# Done-When #7: every non-blank non-comment line -> classified key OR
# explicit unparseable finding. Zero silently dropped means this sum must
# equal the independently-counted total, not the script's own claimed total.
if [[ "$SUM" == "$EXPECTED_TOTAL" ]]; then
  echo "PASS  Done-When #7: CLASSIFIED(${CLASSIFIED_N}) + UNPARSEABLE(${UNPARSEABLE_N}) == ${EXPECTED_TOTAL} non-blank/non-comment lines, zero dropped"
  pass_count=$((pass_count + 1))
else
  echo "FAIL  Done-When #7: CLASSIFIED(${CLASSIFIED_N}) + UNPARSEABLE(${UNPARSEABLE_N}) = ${SUM}, expected ${EXPECTED_TOTAL} — a line was silently dropped"
  fail_count=$((fail_count + 1))
fi

# ══════════════════════════════════════════════════════════════════════════
# CASE B/C/D/E/G — the 3 drift directions, the retirement candidate, the
# stale-consumer-list variant, and the no-secret-value-in-output invariant,
# combined into one fixture set (one env-dir, two registries, one
# consumers-dir) run through a single --audit invocation. Each key below
# exists ONLY to trigger exactly one finding class — see the comment next
# to it. All keys/values are synthetic (FAKE_*).
# ══════════════════════════════════════════════════════════════════════════
CASE_BCDEG="${WORK}/case-bcdeg"
ENV_DIR="${CASE_BCDEG}/env"
REG_DIR="${CASE_BCDEG}/registry"
SRC_DIR="${CASE_BCDEG}/src-fixture"
mkdir -p "$ENV_DIR" "$REG_DIR" "$SRC_DIR"

cat > "${ENV_DIR}/fixture-env-a.env" <<'ENV_EOF'
# synthetic env fixture — fixture-env-a.env
FAKE_UNCLASSIFIED_LIVE_KEY=live-value-not-in-any-registry-001
FAKE_PLAINTEXT_LEAK_KEY=SuperSecretFakeValue123456789
ENV_EOF

cat > "${ENV_DIR}/fixture-env-b.env" <<'ENV_EOF'
# synthetic env fixture — fixture-env-b.env
FAKE_MISLOCATED_SECRET=live-value-mislocated-002
FAKE_DUAL_REGISTERED_KEY=live-value-dual-003
FAKE_RETIRED_SECRET=live-value-retired-004
FAKE_STALE_CONSUMER_KEY=live-value-stale-005
ENV_EOF

# Registry A: mirrors the shape of accounts.md/edge-function-secrets.md after
# the tier/consumers/interval/last_rotated/status columns land. Note the
# trailing Value column is present ONLY for the intentional violation row
# (FAKE_PLAINTEXT_LEAK_KEY) — this is the fixture that stands in for Done-When
# #11 ("no inline plaintext secret value"): a row that SHOULD NOT exist in the
# real registries, reproduced synthetically so the audit's detection of it is
# testable without waiting for a real leak.
cat > "${REG_DIR}/registry-a.md" <<'REG_EOF'
# Fixture Registry A — synthetic, for audit-credential-drift.test.sh only. No real credentials.

| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Value (must be empty) |
|---|---|---|---|---|---|---|---|
| `FAKE_ORPHAN_SECRET` | `fixture-env-a.env` | `service-x` | manual-only | 180d | 2026-01-01 | active | |
| `FAKE_MISLOCATED_SECRET` | `fixture-env-a.env` | `service-y` | manual-only | 180d | 2026-01-01 | active | |
| `FAKE_DUAL_REGISTERED_KEY` | `fixture-env-b.env` | `service-shared` | auto-api | 90d | 2026-02-01 | active | |
| `FAKE_RETIRED_SECRET` | `fixture-env-b.env` | `service-old` | manual-only | 180d | 2025-06-01 | active | |
| `FAKE_STALE_CONSUMER_KEY` | `fixture-env-b.env` | `service-a` | manual-only | 180d | 2025-06-01 | active | |
| `FAKE_PLAINTEXT_LEAK_KEY` | `fixture-env-a.env` | `service-w` | manual-only | 180d | 2026-01-01 | active | `SuperSecretFakeValue123456789` |
REG_EOF

cat > "${REG_DIR}/registry-b.md" <<'REG_EOF'
# Fixture Registry B — synthetic, for audit-credential-drift.test.sh only. No real credentials.

| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Value (must be empty) |
|---|---|---|---|---|---|---|---|
| `FAKE_DUAL_REGISTERED_KEY` | `fixture-env-b.env` | `service-shared` | never-rotate | never | 2025-01-01 | active | |
| `FAKE_REGISTRY_B_ONLY_KEY` | `fixture-env-b.env` | `service-z` | auto-api | 90d | 2026-03-01 | active | |
REG_EOF

# FAKE_STALE_CONSUMER_KEY is documented with 1 consumer (service-a) but has
# 2 live references — the "stale consumer list" drift instance from the
# Problem section. FAKE_RETIRED_SECRET has zero live references anywhere.
cat > "${SRC_DIR}/serviceA.ts" <<'TS_EOF'
const token = Deno.env.get('FAKE_STALE_CONSUMER_KEY');
TS_EOF
cat > "${SRC_DIR}/serviceB.ts" <<'TS_EOF'
const token = Deno.env.get('FAKE_STALE_CONSUMER_KEY');
TS_EOF

echo "--- case B/C/D/E/G: drift directions + retirement + no-value-leak ---"
run_audit "full audit against combined fixture" 1 \
  --audit --env-dir "$ENV_DIR" \
  --registry "${REG_DIR}/registry-a.md" --registry "${REG_DIR}/registry-b.md" \
  --consumers-dir "$SRC_DIR"
# Exit 1 expected: PLAINTEXT_IN_REGISTRY is the one hard-fail finding class
# in this fixture (suggested contract — see header). All other finding
# classes below are informational and do not change the exit code.

assert_out "B  consumer -> registry: live key nobody classified" \
                                       "CONSUMER_ONLY:FAKE_UNCLASSIFIED_LIVE_KEY"
assert_out "C1 registry -> consumer: documented credential, no env entry anywhere" \
                                       "REGISTRY_ONLY:FAKE_ORPHAN_SECRET"
assert_out "C2 registry -> consumer: claims a location it does not occupy" \
                                       "REGISTRY_LOCATION_MISMATCH:FAKE_MISLOCATED_SECRET"
assert_out "C2 detail: mismatch names both the claimed and the found file" \
                                       "claimed=${ENV_DIR}/fixture-env-a.env"
assert_out "D  registry -> registry: same key, two different Tier values" \
                                       "REGISTRY_MISMATCH:FAKE_DUAL_REGISTERED_KEY"
assert_out "E  retirement candidate: registered+present, zero live consumers" \
                                       "RETIREMENT_CANDIDATE:FAKE_RETIRED_SECRET"
assert_out "E2 stale consumer list: documented=1, live=2" \
                                       "CONSUMER_LIST_STALE:FAKE_STALE_CONSUMER_KEY:${REG_DIR}/registry-a.md:documented=1:live=2"
assert_out "Non-Goal violation caught: plaintext value inline in a registry row" \
                                       "PLAINTEXT_IN_REGISTRY:FAKE_PLAINTEXT_LEAK_KEY"

# Done-When #9 — no secret value appears anywhere in the audit output,
# either registry, terminal, or commit. Fingerprint only.
RAW_PLAINTEXT="SuperSecretFakeValue123456789"
EXPECTED_FP="$(_fingerprint "$RAW_PLAINTEXT")"
assert_not_out "Done-When #9: raw plaintext value never appears in output" "$RAW_PLAINTEXT"
assert_out     "Done-When #9: only the fingerprint form appears" "$EXPECTED_FP"

for raw in \
  "live-value-not-in-any-registry-001" \
  "live-value-mislocated-002" \
  "live-value-dual-003" \
  "live-value-retired-004" \
  "live-value-stale-005"
do
  assert_not_out "Done-When #9: consumer-side value '${raw}' never leaks" "$raw"
done

# ══════════════════════════════════════════════════════════════════════════
# CASE F — an unreachable surface is declared, not counted as clean
# (Done-When #2). No live network call: the operator hands the audit a
# known-unreachable surface name + reason via a flag; the invariant under
# test is that the coverage denominator excludes it rather than silently
# crediting it.
# ══════════════════════════════════════════════════════════════════════════
CASE_F="${WORK}/case-f"
ENV_DIR_F="${CASE_F}/env"
SRC_DIR_F="${CASE_F}/src-fixture"
mkdir -p "$ENV_DIR_F" "$SRC_DIR_F"

cat > "${ENV_DIR_F}/fixture-env.env" <<'ENV_EOF'
FAKE_ENUM_TEST_KEY=some-fixture-value-999
ENV_EOF

cat > "${CASE_F}/registry.md" <<'REG_EOF'
# Fixture Registry — synthetic, for audit-credential-drift.test.sh only. No real credentials.

| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Value (must be empty) |
|---|---|---|---|---|---|---|---|
| `FAKE_ENUM_TEST_KEY` | `fixture-env.env` | `service-q` | manual-only | 180d | 2026-01-01 | active | |
REG_EOF

cat > "${SRC_DIR_F}/serviceQ.ts" <<'TS_EOF'
const token = Deno.env.get('FAKE_ENUM_TEST_KEY');
TS_EOF

echo "--- case F: not-enumerated surface excluded from coverage ---"
run_audit "audit with one declared not-enumerated surface" 0 \
  --audit --env-dir "$ENV_DIR_F" --registry "${CASE_F}/registry.md" \
  --consumers-dir "$SRC_DIR_F" \
  --not-enumerated "fixture-ci-secrets:HTTP 403 by design (fixture)"

assert_out "Done-When #2: unreachable surface is named as not-enumerated" \
                                       "NOT_ENUMERATED:fixture-ci-secrets:HTTP 403 by design (fixture)"
assert_out "Done-When #2: coverage denominator excludes the not-enumerated surface" \
                                       "COVERAGE:1/1:not-enumerated=1"
# The wrong-but-tempting behaviors this guards against: silently reading as
# 1/2 (crediting the surface as reachable-but-empty) or 2/2 (crediting it as
# clean). Neither string should ever appear.
assert_not_out "not silently counted as reachable-empty (1/2)" "COVERAGE:1/2"
assert_not_out "not silently counted as clean (2/2)"           "COVERAGE:2/2"

# ══════════════════════════════════════════════════════════════════════════
# CASE I — the two finding classes added specifically to close the CRITICAL
# security findings (relabeled-Value-column, missing-Location-column) had
# zero test coverage until this case (/finish code review, HIGH finding).
# Every prior fixture happened to include both a Value and a Location
# column, so the fix for those CRITICALs ran green without ever being
# exercised by this suite — exactly the gap epistemic.md gate 7b warns
# against. All keys/values synthetic.
# ══════════════════════════════════════════════════════════════════════════
CASE_I="${WORK}/case-i"
ENV_DIR_I="${CASE_I}/env"
REG_DIR_I="${CASE_I}/registry"
mkdir -p "$ENV_DIR_I" "$REG_DIR_I"

cat > "${ENV_DIR_I}/fixture.env" <<'ENV_EOF'
FAKE_NOVALCOL_KEY=some-fixture-value
FAKE_NOLOCCOL_KEY=some-other-fixture-value
FAKE_BUNDLED_KEY_A=bundled-a
FAKE_BUNDLED_KEY_B=bundled-b
ENV_EOF

# Table 1: no Value-like column at all (renamed to "Secret" — the exact
# CRITICAL repro) AND has a Location column, so only the Value-column gap
# is under test here.
cat > "${REG_DIR_I}/registry-i.md" <<'REG_EOF'
# Fixture Registry I — synthetic, for audit-credential-drift.test.sh only. No real credentials.

| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Secret |
|---|---|---|---|---|---|---|---|
| `FAKE_NOVALCOL_KEY` | `fixture.env` | `svc-a` | manual-only | 180d | 2026-01-01 | active | |

| Env var | Consumers | Tier | Interval | Last rotated | Status | Value |
|---|---|---|---|---|---|---|
| `FAKE_NOLOCCOL_KEY` | `svc-b` | manual-only | 180d | 2026-01-01 | active | |

| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Value |
|---|---|---|---|---|---|---|---|
| `FAKE_BUNDLED_KEY_A` / `FAKE_BUNDLED_KEY_B` | `fixture.env` | `svc-c` | manual-only | 180d | 2026-01-01 | active | |
REG_EOF

echo "--- case I: no-Value-column, no-Location-column, and multi-key-bundle findings ---"
run_audit "audit against a registry with 3 differently-shaped tables" 0 \
  --audit --env-dir "$ENV_DIR_I" --registry "${REG_DIR_I}/registry-i.md"

assert_out "no-Value-column table produces PLAINTEXT_CHECK_SKIPPED, not silence" \
                                       "PLAINTEXT_CHECK_SKIPPED:${REG_DIR_I}/registry-i.md"
assert_out "no-Location-column table produces LOCATION_CHECK_SKIPPED, not silence" \
                                       "LOCATION_CHECK_SKIPPED:${REG_DIR_I}/registry-i.md"
# The regression this guards: before the fix, a table with no Location
# column made loc="" for every row, so REGISTRY_LOCATION_MISMATCH fired
# for FAKE_NOLOCCOL_KEY even though it is correctly registered and live.
assert_not_out "no false REGISTRY_LOCATION_MISMATCH for the no-Location-column key" \
                                       "REGISTRY_LOCATION_MISMATCH:FAKE_NOLOCCOL_KEY"
assert_out "genuinely bundled row reports MULTI_KEY_ROW_BUNDLED" \
                                       "MULTI_KEY_ROW_BUNDLED:${REG_DIR_I}/registry-i.md:FAKE_BUNDLED_KEY_A/FAKE_BUNDLED_KEY_B"
# Both bundled keys must still be individually classified/registered —
# the bundling finding is additive information, not a replacement for the
# normal per-key registration the audit otherwise reports.
assert_not_out "bundled key A still has no CONSUMER_ONLY/REGISTRY_ONLY drift" \
                                       "REGISTRY_ONLY:FAKE_BUNDLED_KEY_A"
assert_not_out "bundled key B still has no CONSUMER_ONLY/REGISTRY_ONLY drift" \
                                       "REGISTRY_ONLY:FAKE_BUNDLED_KEY_B"

# Regression guard for the false-positive multi-key bug caught mid-session:
# a "/" in the identifier cell is not always a key separator (e.g. a path).
# None of the split pieces here are valid key-shaped, so this must NOT be
# reported as a bundled row.
CASE_I2="${WORK}/case-i2"
mkdir -p "${CASE_I2}/env" "${CASE_I2}/registry"
echo "FAKE_PATH_LOOKALIKE_KEY=x" > "${CASE_I2}/env/fixture.env"
cat > "${CASE_I2}/registry/registry.md" <<'REG_EOF'
| Env var | Location | Consumers | Tier | Interval | Last rotated | Status | Value |
|---|---|---|---|---|---|---|---|
| `FAKE_PATH_LOOKALIKE_KEY` | OAuth via `~/.config/lookalike/` | `svc-d` | manual-only | 180d | 2026-01-01 | active | |
REG_EOF
run_audit "path-shaped Location cell must not read as a bundled key row" 0 \
  --audit --env-dir "${CASE_I2}/env" --registry "${CASE_I2}/registry/registry.md"
assert_not_out "a '/' in a non-key cell is not a false MULTI_KEY_ROW_BUNDLED" \
                                       "MULTI_KEY_ROW_BUNDLED"

# ══════════════════════════════════════════════════════════════════════════
# CASE J — _safe_echo's own abort path (epistemic.md gate 7: exercise a
# gate's failure path before trusting it). Case H below only greps the
# script's SOURCE for dangerous invocation shapes; this exercises the
# guard function's actual runtime behavior directly.
# ══════════════════════════════════════════════════════════════════════════
echo "--- case J: _safe_echo fails closed on real unsafe input ---"
UNSAFE_DIR="${WORK}/case-j/env>weird"
mkdir -p "$UNSAFE_DIR"
echo "FAKE_UNSAFE_PATH_KEY=x" > "${UNSAFE_DIR}/fixture.env"
UNSAFE_OUT="$("$SCRIPT" --parse-only --env-dir "$UNSAFE_DIR" 2>&1)"
UNSAFE_EXIT=$?
if [[ "$UNSAFE_EXIT" == "3" ]] && printf '%s' "$UNSAFE_OUT" | grep -qF "FATAL: audit-credential-drift.sh attempted unsafe output"; then
  echo "PASS  _safe_echo aborts with exit 3 + FATAL message on real unsafe output"
  pass_count=$((pass_count + 1))
else
  echo "FAIL  _safe_echo did not fail closed: exit=${UNSAFE_EXIT}"
  printf '%s\n' "$UNSAFE_OUT" | sed 's/^/        /'
  fail_count=$((fail_count + 1))
fi

# ══════════════════════════════════════════════════════════════════════════
# CASE H — static guards for the Non-Goals (never `source`s an env file,
# never puts a secret-looking var directly into an executed command's argv).
# Heuristic, grep-based, in the same spirit as this repo's other static
# self-checks (e.g. check-edge-function-secrets.sh's `is_builtin` allowlist).
# This does NOT prove the absence of every possible leak path — a human
# reviewer should still eyeball any new exec call the script gains.
# ══════════════════════════════════════════════════════════════════════════
echo "--- case H: static safety guards (Non-Goals) ---"

if grep -nE '(^|[^#[:alnum:]_])(source|\.)[[:space:]]+[^&|;]*\.env([^A-Za-z0-9_]|$)' "$SCRIPT" \
    | grep -v '^\s*[0-9]*:\s*#'; then
  echo "FAIL  no-source-on-env-file: found a source/. invocation of an .env file"
  fail_count=$((fail_count + 1))
else
  echo "PASS  no-source-on-env-file: script never sources an env file (2026-08-21 incident class)"
  pass_count=$((pass_count + 1))
fi

if grep -nE '\b(curl|wget|http|aws|gcloud|ssh)\b[^\n]*\$\{?[A-Za-z_][A-Za-z0-9_]*(SECRET|VALUE|PASSWORD|TOKEN|_KEY)\}?' "$SCRIPT"; then
  echo "FAIL  no-secret-as-argv: a *SECRET*/*VALUE*/*PASSWORD*/*TOKEN*/*_KEY* var appears inline in an executed command's arguments (ps-visible)"
  fail_count=$((fail_count + 1))
else
  echo "PASS  no-secret-as-argv (heuristic grep — not a proof; still eyeball any new exec call in review)"
  pass_count=$((pass_count + 1))
fi

if grep -nE '\bmint\b|\brotate\b|\brevoke\b' "$SCRIPT" | grep -viE 'never-?rotate|# |comment'; then
  echo "FAIL  read-only guard: script source mentions mint/rotate/revoke outside comments — check it isn't writing credentials"
  fail_count=$((fail_count + 1))
else
  echo "PASS  read-only guard: no mint/rotate/revoke verbs found in executable code"
  pass_count=$((pass_count + 1))
fi

echo ""
echo "=== ${pass_count} passed, ${fail_count} failed ==="
[[ "$fail_count" -eq 0 ]] || exit 1
exit 0
